### ISSUE TITLE
viewing remote images inline

### ISSUE THREAD

**Issue by jingxuanlim** [kitchoi/org-mode#1]
Hi @kitchoi, I refer to your [2014 thread here](https://lists.gnu.org/archive/html/emacs-orgmode/2014-11/msg00583.html) about viewing remote images inline. This seems to be what I'm looking for.

When working with a remote org-mode file over tramp, org-mode's default behavior is to show a black box when `M-x  org-toggle-inline-images` is evoked on a relative (non-remote) image link. When the link is accessed using e.g. `C-x C-o` or more specifically, `M-x org-open-at-point`, org-mode rightly pulls the image using tramp and shows it in another another window.

I can't read elisp, but from what I understand from your thread with Michael Albinus, this should allow me to view inline images that exist remotely. This relies on tramp, as if `M-x org-open-at-point` was invoked, but the image will appear inline as opposed to in another window. The image is downloaded the first time it is viewed, but a locally copy could be saved in a temp directory for fast subsequent loading.

If this is true, this is amazing and has been something I wanted for a very long time!

I'd love to apply this [patch](https://github.com/kitchoi/org-mode/commit/2e600da455c371754f028ddaaed1ae1724cbe6b6) you've written. How do you suggest I do this?

**Comment by jingxuanlim** [comment]
Okay, I just renamed and added your redefined `org-display-inline-images` into my init file -- and it works amazingly! Thank you so much for writing this!!

**Comment by jingxlim** [comment]
Sorry for the spam, but I just noticed that part of that function changes the link to one that org-mode would recognize (e.g. `/ssh:`). But this takes away the ability to view the file "locally" on that remote machine, doesn't it?

**Comment by kitchoi** [comment]
Hi @jingxlim 
Thank you very much for the message! I am glad that someone found this useful, and the fact that it still works after 6 years. It was a long time ago so I don't remember exactly how I incorporated the change with my workflow then. I might have just modified source package in-place. Redefining it in the init file sounds like a decent alternative to me.

**Comment by jingxuanlim** [comment]
Thanks for your comments. It has been working fantastic for me so far so I think I'll be fine. Thanks again!!
